[build]
target = "riscv32imac-unknown-none-elf"

[target.riscv32imac-unknown-none-elf]
linker = "riscv64-unknown-elf-gcc"
rustflags = [
    "-C", "link-arg=-mabi=ilp32",
    "-C", "link-arg=-march=rv32imac",
    "-C", "link-arg=-ffreestanding",
    "-C", "link-arg=-nostdlib",
    "-C", "panic=abort",
    "-C", "opt-level=z",
    "-C", "relocation-model=static",
    "-C", "link-arg=-Wl,--gc-sections",
    "-C", "link-arg=-nostartfiles",
    "-C", "link-arg=-Wl,-O3",
    "-C", "link-arg=-fno-pie",
    "-C", "link-arg=-no-pie",
]
